### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by Phoenixxl** [CSSEGISandData/2019-nCoV#12]
Thank you so much for providing us with this data.

I don't see what the issue was with google sheets though. I'm sure anyone who used this data could convert import export it in any way they wanted.

Every time you choose to stop one method of delivery and select to chose a new one brings a new challenge, that is very good for learning new skills. I've never imported and integrity checked csv files from github into google sheets before.

I would appreciate though, for the future, to either keep supporting the previously offered delivery formats or sticking with the current one. Maybe start a reddit or other "user support" page where people who are unable to get what they need can ask others how they can achieve what they want?

If they wanted to be able to download a CSV from your published sheet it was as easy as creating an empty google docs sheet file, importing your 3 tabs to it then saving it as a csv file from there.
Someone would have taken the time to explain them how to do it, I'm sure.

Again, thank you so much for taking the time to centralize all this data and keeping it up to date for us.

Friendly regards.
A

**Comment by Bost** [comment]
https://github.com/CSSEGISandData/COVID-19/issues/238
