### ISSUE TITLE
Using Semicolon as Delimiter

### ISSUE THREAD

**Issue by marvinsirait** [CSSEGISandData/2019-nCoV#14]
Dear Contributors,

Because of some province/state have comma, I think it will be much better to use semicolon as delimiter (like the format you use before current format).

Thank you.

**Comment by marvinsirait** [comment]
Nevermind, you've already add quote to that particular province/state so it is just fine.

**Comment by ciscorucinski** [comment]
Most APIs that read CSV files will ignore commas that are inside of quotes. If you look at the raw `Province/State` column you will see that those with commas have quotes
