### ISSUE TITLE
Missing column in `time_series_2019-ncov - Recovered.csv`

### ISSUE THREAD

**Issue by benmaier** [CSSEGISandData/2019-nCoV#2]
Thank you so much for putting up the raw data!

I've noticed that in the file `time_series_2019-ncov - Recovered.csv`, the column with time stamp `1/31/2020 7:00 PM` is missing while it's present in the corresponding `Death`- and `Confirmed`-files. Would you be able to comment on why that is?

I've noticed that the time stamp `1/31/2020 7:00 PM` is missing in the daily update data, as well.

Thanks again!

**Comment by CSSEGISandData** [comment]
Hello,

Good catch. Yes, we have to remove the recovered data for 1/31/2019 7 pm
since the original data is incomplete. They are missing the recovered data
for Hubei Province, and several other data are inconsistent with other time
periods.

Thanks!
Frank

**Comment by benmaier** [comment]
Ok, thanks for the quick reply!
